//Maincategory

export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY"
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"
export const GET_MAINCATEGORY = "GET_MAINCATEGORY"
export const UPDATE_MAINCATEGORY = "UPDATE_MAINCATEGORY"
export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY"

